---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: planet-tracker-app
  namespace: picard-sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: planet-tracker-app
  template:
    metadata:
      labels:
        app: planet-tracker-app
    spec:
      containers:
        - name: planet-tracker-app
          image: violabs/enterprise-planet-tracker:0.0.2-SNAPSHOT
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: postgres-credentials
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: postgres-credentials
            - name: POSTGRES_HOST
              value: "postgres"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "postgres"

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: picard-sandbox
type: OPAQUE
data:
  username: cG9zdGdyZXM=
  password: cGFzc3dvcmQ=

---
apiVersion: v1
kind: Service
metadata:
  name: planet-tracker-app-service
  namespace: picard-sandbox
spec:
  selector:
    app: planet-tracker-app
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
