package io.violabs.konstellation.metaDsl.annotation

/**
 * Annotation to mark classes that are generated by the DSL processor.
 */
@Target(AnnotationTarget.CLASS)
@Retention(AnnotationRetention.SOURCE)
annotation class GeneratedDsl(
    val withListGroup: Boolean = false,
    val withMapGroup: String = MapGroupTypes.NONE,
    val isRoot: Boolean = false
) {
    /**
     * Constants representing the different types of map groups.
     */
    object MapGroupTypes {
        const val NONE = "NONE"
        const val SINGLE = "SINGLE"
        const val LIST = "LIST"
        const val ALL = "ALL"
    }

    /**
     * Enum representing the types of map groups.
     */
    enum class MapGroupType {
        NONE, SINGLE, LIST, ALL;

        companion object {
            val ACTIVE_TYPES: List<MapGroupType?> = listOf(SINGLE, LIST, ALL)
        }
    }
}
